<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAggregateControllerQueryProviderFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'TheCodingMachine\GraphQLite\AggregateControllerQueryProviderFactory' shared autowired service.
     *
     * @return \TheCodingMachine\GraphQLite\AggregateControllerQueryProviderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/QueryProviderFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/AggregateControllerQueryProviderFactory.php';

        return $container->privates['TheCodingMachine\\GraphQLite\\AggregateControllerQueryProviderFactory'] = new \TheCodingMachine\GraphQLite\AggregateControllerQueryProviderFactory([0 => 'TheCodingMachine\\Graphqlite\\Bundle\\Controller\\GraphQL\\LoginController', 1 => 'TheCodingMachine\\Graphqlite\\Bundle\\Controller\\GraphQL\\MeController'], $container);
    }
}
