<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_ExecutorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.executor' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Executor.php';

        return $container->privates['api_platform.graphql.executor'] = new \ApiPlatform\Core\GraphQl\Executor();
    }
}
