<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_SensioFrameworkExtra_Psr7_ArgumentValueResolver_ServerRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.sensio_framework_extra.psr7.argument_value_resolver.server_request' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

        return $container->privates['debug.sensio_framework_extra.psr7.argument_value_resolver.server_request'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(($container->privates['debug.sensio_framework_extra.psr7.argument_value_resolver.server_request.inner'] ?? $container->load('getDebug_SensioFrameworkExtra_Psr7_ArgumentValueResolver_ServerRequest_InnerService')), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
    }
}
