<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'TheCodingMachine\Graphqlite\Bundle\Controller\GraphQL\LoginController' shared autowired service.
     *
     * @return \TheCodingMachine\Graphqlite\Bundle\Controller\GraphQL\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-bundle/Controller/GraphQL/LoginController.php';

        return $container->services['TheCodingMachine\\Graphqlite\\Bundle\\Controller\\GraphQL\\LoginController'] = new \TheCodingMachine\Graphqlite\Bundle\Controller\GraphQL\LoginController(($container->privates['security.user.provider.concrete.app_user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_AppUserProviderService')), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['session'] ?? $container->load('getSessionService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), 'main');
    }
}
