<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Maker\Migrator' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Maker\Migrator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Maker/Migrator.php';

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Maker\\Migrator'] = new \EasyCorp\Bundle\EasyAdminBundle\Maker\Migrator();
    }
}
