<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestParameterMiddlewareService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'TheCodingMachine\Graphqlite\Bundle\Mappers\RequestParameterMiddleware' shared autowired service.
     *
     * @return \TheCodingMachine\Graphqlite\Bundle\Mappers\RequestParameterMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/Mappers/Parameters/ParameterMiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-bundle/Mappers/RequestParameterMiddleware.php';

        return $container->privates['TheCodingMachine\\Graphqlite\\Bundle\\Mappers\\RequestParameterMiddleware'] = new \TheCodingMachine\Graphqlite\Bundle\Mappers\RequestParameterMiddleware();
    }
}
