<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyUserInterfaceTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'TheCodingMachine\Graphqlite\Bundle\Types\SymfonyUserInterfaceType' shared autowired service.
     *
     * @return \TheCodingMachine\Graphqlite\Bundle\Types\SymfonyUserInterfaceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-bundle/Types/SymfonyUserInterfaceType.php';

        return $container->services['TheCodingMachine\\Graphqlite\\Bundle\\Types\\SymfonyUserInterfaceType'] = new \TheCodingMachine\Graphqlite\Bundle\Types\SymfonyUserInterfaceType();
    }
}
