<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticTypeMapperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'TheCodingMachine\GraphQLite\Mappers\StaticTypeMapper' shared autowired service.
     *
     * @return \TheCodingMachine\GraphQLite\Mappers\StaticTypeMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/Mappers/TypeMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/Mappers/StaticTypeMapper.php';

        return $container->privates['TheCodingMachine\\GraphQLite\\Mappers\\StaticTypeMapper'] = new \TheCodingMachine\GraphQLite\Mappers\StaticTypeMapper();
    }
}
