<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestUsersRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ApiPlatform\Repository\TestUsersRepository' shared autowired service.
     *
     * @return \App\ApiPlatform\Repository\TestUsersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Security/User/UserLoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ApiPlatform/Repository/TestUsersRepository.php';

        return $container->privates['App\\ApiPlatform\\Repository\\TestUsersRepository'] = new \App\ApiPlatform\Repository\TestUsersRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
