<?php

namespace ContainerTpY3wNE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestScheduledShiftsRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ApiPlatform\Repository\TestScheduledShiftsRepository' shared autowired service.
     *
     * @return \App\ApiPlatform\Repository\TestScheduledShiftsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/ApiPlatform/Repository/TestScheduledShiftsRepository.php';

        return $container->privates['App\\ApiPlatform\\Repository\\TestScheduledShiftsRepository'] = new \App\ApiPlatform\Repository\TestScheduledShiftsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
