# Read more about GraphQLite available options at: https://graphqlite.thecodingmachine.io/docs/symfony-bundle
graphqlite:
  security:
    firewall_name: main
    enable_login: auto
    enable_me: auto
  namespace:
    controllers: App\GraphqlController\
    types:
      - App\Types
      - App\Entity
