<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Resolver_ResourceFieldService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.resolver.resource_field' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Resolver\ResourceFieldResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/ResourceFieldResolver.php';

        return $container->privates['api_platform.graphql.resolver.resource_field'] = new \ApiPlatform\Core\GraphQl\Resolver\ResourceFieldResolver(($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()));
    }
}
