<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssertParameterMiddlewareService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'TheCodingMachine\Graphqlite\Validator\Mappers\Parameters\AssertParameterMiddleware' shared autowired service.
     *
     * @return \TheCodingMachine\Graphqlite\Validator\Mappers\Parameters\AssertParameterMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/Mappers/Parameters/ParameterMiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-symfony-validator-bridge/src/Mappers/Parameters/AssertParameterMiddleware.php';

        return $container->privates['TheCodingMachine\\Graphqlite\\Validator\\Mappers\\Parameters\\AssertParameterMiddleware'] = new \TheCodingMachine\Graphqlite\Validator\Mappers\Parameters\AssertParameterMiddleware(($container->privates['validator.validator_factory'] ?? $container->getValidator_ValidatorFactoryService()), ($container->services['validator'] ?? $container->getValidatorService()), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
