<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Serializer_ContextBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.serializer.context_builder' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Serializer\SerializerContextBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Serializer/SerializerContextBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Serializer/SerializerContextBuilder.php';

        return $container->privates['api_platform.graphql.serializer.context_builder'] = new \ApiPlatform\Core\GraphQl\Serializer\SerializerContextBuilder(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['serializer.name_converter.metadata_aware'] ?? $container->getSerializer_NameConverter_MetadataAwareService()));
    }
}
