<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Resolver_Stage_ReadService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.resolver.stage.read' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Resolver\Stage\ReadStage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ReadStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ReadStage.php';

        return $container->privates['api_platform.graphql.resolver.stage.read'] = new \ApiPlatform\Core\GraphQl\Resolver\Stage\ReadStage(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()), ($container->privates['debug.api_platform.collection_data_provider'] ?? $container->getDebug_ApiPlatform_CollectionDataProviderService()), ($container->privates['debug.api_platform.subresource_data_provider'] ?? $container->getDebug_ApiPlatform_SubresourceDataProviderService()), ($container->privates['api_platform.graphql.serializer.context_builder'] ?? $container->load('getApiPlatform_Graphql_Serializer_ContextBuilderService')), '_');
    }
}
