<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGraphqlite_Psr16cacheService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'graphqlite.psr16cache' shared autowired service.
     *
     * @return \Symfony\Component\Cache\Psr16Cache
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/simple-cache/src/CacheInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/cache/Psr16Cache.php';

        return $container->privates['graphqlite.psr16cache'] = new \Symfony\Component\Cache\Psr16Cache(($container->privates['graphqlite.phpfilescache'] ?? $container->load('getGraphqlite_PhpfilescacheService')));
    }
}
