<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchemaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'TheCodingMachine\GraphQLite\Schema' shared autowired service.
     *
     * @return \TheCodingMachine\GraphQLite\Schema
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Schema.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite/src/Schema.php';

        return $container->services['TheCodingMachine\\GraphQLite\\Schema'] = ($container->privates['TheCodingMachine\\GraphQLite\\SchemaFactory'] ?? $container->load('getSchemaFactoryService'))->createSchema();
    }
}
