<?php

namespace Container5ATxelD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServerConfigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'GraphQL\Server\ServerConfig' shared autowired service.
     *
     * @return \TheCodingMachine\Graphqlite\Bundle\Server\ServerConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Server/ServerConfig.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-bundle/Server/ServerConfig.php';

        $container->privates['GraphQL\\Server\\ServerConfig'] = $instance = new \TheCodingMachine\Graphqlite\Bundle\Server\ServerConfig();

        $instance->setSchema(($container->services['TheCodingMachine\\GraphQLite\\Schema'] ?? $container->load('getSchemaService')));
        $instance->setErrorFormatter([0 => '\\TheCodingMachine\\GraphQLite\\Exceptions\\WebonyxErrorHandler', 1 => 'errorFormatter']);
        $instance->setErrorsHandler([0 => '\\TheCodingMachine\\GraphQLite\\Exceptions\\WebonyxErrorHandler', 1 => 'errorHandler']);
        $instance->setDebug(8);
        $instance->setValidationRules([]);

        return $instance;
    }
}
