<?php

namespace ContainerEQUhxVp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9YiiIgCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9YiiIgC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9YiiIgC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SecurityController::loginAPI' => ['privates', '.service_locator.p4vlack', 'get_ServiceLocator_P4vlackService', true],
            'App\\Controller\\SecurityController::logout' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\SecurityController::testLogin' => ['privates', '.service_locator.MHtnt5Y', 'get_ServiceLocator_MHtnt5YService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\SecurityController:loginAPI' => ['privates', '.service_locator.p4vlack', 'get_ServiceLocator_P4vlackService', true],
            'App\\Controller\\SecurityController:logout' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\SecurityController:testLogin' => ['privates', '.service_locator.MHtnt5Y', 'get_ServiceLocator_MHtnt5YService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\SecurityController::loginAPI' => '?',
            'App\\Controller\\SecurityController::logout' => '?',
            'App\\Controller\\SecurityController::testLogin' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SecurityController:loginAPI' => '?',
            'App\\Controller\\SecurityController:logout' => '?',
            'App\\Controller\\SecurityController:testLogin' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
