<?php

namespace ContainerEQUhxVp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_FieldsBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.fields_builder' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Type\FieldsBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/FieldsBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/FieldsBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypeBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypeBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/ResourceFieldResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypeConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypeConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ResolverFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ItemResolverFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ReadStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ReadStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Serializer/SerializerContextBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Serializer/SerializerContextBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SecurityStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SecurityStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SecurityPostDenormalizeStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SerializeStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SerializeStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/DeserializeStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/DeserializeStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/WriteStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/WriteStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ValidateStageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Resolver/Stage/ValidateStage.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypesContainerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Type/TypesContainer.php';

        $a = ($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService());
        $b = ($container->privates['api_platform.graphql.types_container'] ?? ($container->privates['api_platform.graphql.types_container'] = new \ApiPlatform\Core\GraphQl\Type\TypesContainer()));
        $c = ($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService());

        $d = new \ApiPlatform\Core\GraphQl\Type\TypeBuilder($b, new \ApiPlatform\Core\GraphQl\Resolver\ResourceFieldResolver($c), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'api_platform.graphql.fields_builder' => ['privates', 'api_platform.graphql.fields_builder', 'getApiPlatform_Graphql_FieldsBuilderService', true],
        ], [
            'api_platform.graphql.fields_builder' => '?',
        ]));
        $e = ($container->privates['serializer.name_converter.metadata_aware'] ?? $container->getSerializer_NameConverter_MetadataAwareService());

        $f = new \ApiPlatform\Core\GraphQl\Serializer\SerializerContextBuilder($a, $e);

        $g = new \ApiPlatform\Core\GraphQl\Resolver\Stage\ReadStage($a, $c, ($container->privates['debug.api_platform.collection_data_provider'] ?? $container->getDebug_ApiPlatform_CollectionDataProviderService()), ($container->privates['debug.api_platform.subresource_data_provider'] ?? $container->getDebug_ApiPlatform_SubresourceDataProviderService()), $f, '_');
        $h = ($container->privates['api_platform.security.resource_access_checker'] ?? $container->getApiPlatform_Security_ResourceAccessCheckerService());

        $i = new \ApiPlatform\Core\GraphQl\Resolver\Stage\SecurityStage($a, $h);
        $j = new \ApiPlatform\Core\GraphQl\Resolver\Stage\SecurityPostDenormalizeStage($a, $h);
        $k = ($container->services['serializer'] ?? $container->getSerializerService());
        $l = ($container->privates['api_platform.pagination'] ?? $container->load('getApiPlatform_PaginationService'));

        $m = new \ApiPlatform\Core\GraphQl\Resolver\Stage\SerializeStage($a, $k, $f, $l);
        $n = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []);

        return $container->privates['api_platform.graphql.fields_builder'] = new \ApiPlatform\Core\GraphQl\Type\FieldsBuilder(($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $container->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Property_MetadataFactory_CachedService()), $a, $b, $d, new \ApiPlatform\Core\GraphQl\Type\TypeConverter($d, $b, $a), new \ApiPlatform\Core\GraphQl\Resolver\Factory\ItemResolverFactory($g, $i, $j, $m, $n, $a), new \ApiPlatform\Core\GraphQl\Resolver\Factory\CollectionResolverFactory($g, $i, $j, $m, $n, $a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))), new \ApiPlatform\Core\GraphQl\Resolver\Factory\ItemMutationResolverFactory($g, $i, $j, $m, new \ApiPlatform\Core\GraphQl\Resolver\Stage\DeserializeStage($a, $k, $f), new \ApiPlatform\Core\GraphQl\Resolver\Stage\WriteStage($a, ($container->privates['debug.api_platform.data_persister'] ?? $container->getDebug_ApiPlatform_DataPersisterService()), $f), new \ApiPlatform\Core\GraphQl\Resolver\Stage\ValidateStage($a, ($container->privates['api_platform.validator'] ?? $container->load('getApiPlatform_ValidatorService'))), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []), $a), ($container->privates['api_platform.filter_locator'] ?? $container->getApiPlatform_FilterLocatorService()), $l, $e, '_');
    }
}
