<?php

namespace Container6mqQtUC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOverblogGraphiql_ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'overblog_graphiql.controller' shared service.
     *
     * @return \Overblog\GraphiQLBundle\Controller\GraphiQLController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphiql-bundle/Controller/GraphiQLController.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphiql-bundle/Config/GraphiQLViewConfig.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphiql-bundle/Config/GraphiQLViewJavaScriptLibraries.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphiql-bundle/Config/GraphiQLControllerEndpoint.php';
        include_once \dirname(__DIR__, 4).'/vendor/thecodingmachine/graphqlite-bundle/GraphiQL/EndpointResolver.php';

        return $container->services['overblog_graphiql.controller'] = new \Overblog\GraphiQLBundle\Controller\GraphiQLController(($container->services['twig'] ?? $container->getTwigService()), new \Overblog\GraphiQLBundle\Config\GraphiQLViewConfig(new \Overblog\GraphiQLBundle\Config\GraphiQLViewJavaScriptLibraries('0.11', '15.6', '2.0'), '@OverblogGraphiQL/GraphiQL/index.html.twig'), new \TheCodingMachine\Graphqlite\Bundle\GraphiQL\EndpointResolver(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))));
    }
}
