<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEQUhxVp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEQUhxVp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEQUhxVp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEQUhxVp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEQUhxVp\App_KernelDevDebugContainer([
    'container.build_hash' => 'EQUhxVp',
    'container.build_id' => '1ad20503',
    'container.build_time' => 1603695859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEQUhxVp');
